name: Hospital API CI

on:
  push:
    branches: [main]
    paths:
      - "src/apps/hospital/api/**"
  pull_request:
    branches: [main]
    types: [opened,synchronize,reopened]
    paths:
      - "src/apps/hospital/api/**"
  workflow_dispatch:
jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16.14.2'
      - name: Install dependencies ğŸ“¦
        run: npm ci --loglevel=error
      - name: Lint ğŸ”
        run: npm run lint -w api
      - name: Build ğŸ—ï¸
        run: |
            npm run build -w core
            npm run build:back -w hospital
            npm run build -w api
      - name: Create env file for E2E tests ğŸ§ª
        run: |
            cd ./src/apps/hospital/api/src/environments
            touch test.env
            echo "${{ secrets.DEV_ENV }}" | base64 --decode > test.env
      - name: Start Docker Compose ğŸ³
        run: docker-compose run --rm -d --service-ports hospital-api
      - name: Wait for API to start
        run: sleep 5
      - name: E2E tests ğŸ§ª
        run: npm run test -w api
      - name: SonarCloud Scan ğŸ“Š
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ github.token }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: src/apps/hospital/api
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main'}}
    steps:
      - name: Deploiy
        run: echo "Deploying..."

